<?php
/**
 * Created by PhpStorm.
 * User: rahul
 * Date: 1/31/2016
 * Time: 1:27 AM
 */

namespace RTool\UserBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class BlogType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        #parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder->add('title', 'Symfony\Component\Form\Extension\Core\Type\TextType', ['label' => 'Blog Title'])
                ->add('summary', 'Symfony\Component\Form\Extension\Core\Type\TextareaType',['label' => 'Summary', 'attr' => ['rows' => 5]])
                ->add('content', 'Symfony\Component\Form\Extension\Core\Type\TextareaType', ['label' => 'Content', 'attr' => ['rows' => 15]])
                ->setAction("");
    }


    public function getBlockPrefix()
    {
        #return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
        return 'app_blog';
    }


    public function getName()
    {
        #return parent::getName(); // TODO: Change the autogenerated stub
        return 'app_blog';
    }
}